#!/bin/bash

##ENVIRONMENT SETTINGS; CHANGE WITH CAUTION

#SBATCH --export=NONE                   # Do not propagate environment
#SBATCH --get-user-env=L                # Replicate login environment

##NECESSARY JOB SPECIFICATIONS

#SBATCH --job-name=gGAN
#SBATCH --time=40:00:00
#SBATCH --ntasks=1
#SBATCH --mem=2G
#SBATCH --output=stdout.%j
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu

##OPTIONAL JOB SPECIFICATIONS

#SBATCH --account=122816061899
#SBATCH --mail-type=ALL
#SBATCH --mail-user=caio.davi@tamu.edu

# load required module(s)
module load CUDA/9.2.148.1
module load Anaconda/3-5.0.0.1

# activate environment
source activate gGAN-0.0.1

# run your program
../src/gGAN --afd 1.00 run
